# Generated by Django 2.2.7 on 2020-08-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssapp', '0003_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='published',
            field=models.CharField(default='', max_length=20),
        ),
    ]
